/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bcd6f475-ebf7-41a1-a519-92171f126f09",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rxQUTw4b3",
    "aws_user_pools_web_client_id": "5mlmnlk7nbvtra1bt3ugki9vb3",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://kiyoupd2bffgvbxamtkok43tha.appsync-api.us-east-1.amazonaws.com/graphql",
    "aws_appsync_region": "us-east-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-t6kwbrpiszhkrosl7kzd2alcru",
    "aws_user_files_s3_bucket": "amplify-tjps4-dev-90841-deployment90841-dev",
    "aws_user_files_s3_bucket_region": "us-east-1"
};


export default awsmobile;
