/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:bcd6f475-ebf7-41a1-a519-92171f126f09",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_rxQUTw4b3",
    "aws_user_pools_web_client_id": "5mlmnlk7nbvtra1bt3ugki9vb3",
    "oauth": {}
};


export default awsmobile;
